/**
 * ORCA Marine Conservation & Species Intelligence Dataset
 * Real Indian Ocean & Arabian Sea Marine Species & Ecological Incident Telemetry
 */

const ORCA_SPECIES_CATALOG = [
  {
    id: "sp-blue-whale",
    name_en: "Blue Whale",
    name_hi: "नीली व्हेल (Blue Whale)",
    name_ta: "நீலத் திமிங்கிலம்",
    scientific: "Balaenoptera musculus",
    category: "mammal",
    icon: "🐋",
    iucn: "endangered",
    iucn_label_en: "Endangered",
    iucn_label_hi: "विलुप्तप्राय (Endangered)",
    iucn_label_ta: "அழிந்துவரும் இனம்",
    detections_24h: 3,
    total_tracked: 14,
    last_coords: [15.18, 73.45],
    last_location_en: "Goa Offshore Deep Trench (26 NM)",
    last_location_hi: "गोवा अपतटीय गहरा खड्ड (26 समुद्री मील)",
    last_location_ta: "கோவா ஆழ்கடல் பகுதி (26 கடல் மைல்)",
    acoustic_freq: "16 - 22 Hz (Infra-acoustic)",
    swim_speed: "8.4 kts",
    dive_depth: "185 m",
    protection_status_en: "Schedule I — Wildlife Protection Act",
    bio_note_en: "Mother and calf pair tracked migrating south along continental shelf edge. Thermal front correlation active."
  },
  {
    id: "sp-olive-ridley",
    name_en: "Olive Ridley Sea Turtle",
    name_hi: "ओलिव रिडले समुद्री कछुआ",
    name_ta: "ஆலிவ் ரிட்லி கடல் ஆமை",
    scientific: "Lepidochelys olivacea",
    category: "reptile",
    icon: "🐢",
    iucn: "vulnerable",
    iucn_label_en: "Vulnerable",
    iucn_label_hi: "संवेदनशील (Vulnerable)",
    iucn_label_ta: "பாதிக்கப்படக்கூடிய இனம்",
    detections_24h: 42,
    total_tracked: 289,
    last_coords: [15.58, 73.74],
    last_location_en: "Morjim Coastal Nesting Biosphere",
    last_location_hi: "मोरजिम तटीय घोंसला बायोस्फीयर",
    last_location_ta: "மோர்ஜிம் கடற்கரை கூடுகட்டும் பகுதி",
    acoustic_freq: "N/A (Satellite ARGOS Tag)",
    swim_speed: "2.1 kts",
    dive_depth: "34 m",
    protection_status_en: "Schedule I — Protected Mass Nesting Site",
    bio_note_en: "Breeding aggregation approaching coastal shallows. Trawler exclusion zone enforced within 5 km."
  },
  {
    id: "sp-whale-shark",
    name_en: "Whale Shark",
    name_hi: "व्हेल शार्क (Rhincodon typus)",
    name_ta: "திமிங்கில சுறா",
    scientific: "Rhincodon typus",
    category: "fish",
    icon: "🦈",
    iucn: "endangered",
    iucn_label_en: "Endangered",
    iucn_label_hi: "विलुप्तप्राय (Endangered)",
    iucn_label_ta: "அழிந்துவரும் இனம்",
    detections_24h: 5,
    total_tracked: 31,
    last_coords: [15.35, 73.62],
    last_location_en: "Grande Island Pelagic Front",
    last_location_hi: "ग्रैंडे द्वीप पेलाजिक फ्रंट",
    last_location_ta: "கிராண்டே தீவு கடல் பகுதி",
    acoustic_freq: "Hydrophone Tag #WS-88",
    swim_speed: "3.6 kts",
    dive_depth: "92 m",
    protection_status_en: "Highest Legal Protection (CITES App I)",
    bio_note_en: "Plankton surface skimming observed. Water temperature optimal at 28.4°C."
  },
  {
    id: "sp-bottlenose-dolphin",
    name_en: "Indo-Pacific Bottlenose Dolphin",
    name_hi: "इंडो-पैसिफिक बॉटलनोज़ डॉल्फ़िन",
    name_ta: "டால்பின்",
    scientific: "Tursiops aduncus",
    category: "mammal",
    icon: "🐬",
    iucn: "protected",
    iucn_label_en: "Protected",
    iucn_label_hi: "संरक्षित (Protected)",
    iucn_label_ta: "பாதுகாக்கப்பட்ட இனம்",
    detections_24h: 68,
    total_tracked: 195,
    last_coords: [15.42, 73.78],
    last_location_en: "Mormugao Coastal Estuary",
    last_location_hi: "मोरमुगाओ तटीय मुहाना",
    last_location_ta: "மோர்முகாவோ முகத்துவாரம்",
    acoustic_freq: "28 - 130 kHz (Sonar clicks)",
    swim_speed: "11.2 kts",
    dive_depth: "22 m",
    protection_status_en: "Marine Mammal Sanctuary Zone",
    bio_note_en: "Resident pod active in cooperative schooling fish hunting near estuary mouth."
  },
  {
    id: "sp-coral-sanctuary",
    name_en: "Malvan Coral Reef Reserve",
    name_hi: "मालवण प्रवाल भित्ति अभयारण्य",
    name_ta: "பவளப்பாறை சரணாலயம்",
    scientific: "Acropora & Porites Habitat",
    category: "habitat",
    icon: "🪸",
    iucn: "vulnerable",
    iucn_label_en: "Critical Habitat",
    iucn_label_hi: "गंभीर आवास (Critical)",
    iucn_label_ta: "முக்கிய வாழ்விடம்",
    detections_24h: 1,
    total_tracked: 8,
    last_coords: [16.06, 73.47],
    last_location_en: "Malvan Marine Protected Zone",
    last_location_hi: "मालवण समुद्री संरक्षित क्षेत्र",
    last_location_ta: "மால்வன் பாதுகாக்கப்பட்ட கடல் பகுதி",
    acoustic_freq: "Eco-Acoustic Health Index: 78/100",
    swim_speed: "Static Reef",
    dive_depth: "8 - 18 m",
    protection_status_en: "Marine National Park Protected Reef",
    bio_note_en: "Live coral cover 42%. Low bleaching alert. Water turbidity within nominal tolerance."
  },
  {
    id: "sp-dugong",
    name_en: "Dugong (Sea Cow)",
    name_hi: "डुगोंग (समुद्री गाय)",
    name_ta: "கடற்பசு (Dugong)",
    scientific: "Dugong dugon",
    category: "mammal",
    icon: "🦭",
    iucn: "vulnerable",
    iucn_label_en: "Vulnerable",
    iucn_label_hi: "संवेदनशील (Vulnerable)",
    iucn_label_ta: "பாதிக்கப்படக்கூடிய இனம்",
    detections_24h: 2,
    total_tracked: 12,
    last_coords: [9.28, 79.15],
    last_location_en: "Gulf of Mannar Seagrass Bed",
    last_location_hi: "मन्नार की खाड़ी समुद्री घास क्षेत्र",
    last_location_ta: "மன்னார் வளைகுடா கடல்புல் பகுதி",
    acoustic_freq: "1 - 8 kHz (Chirp & bark)",
    swim_speed: "2.8 kts",
    dive_depth: "12 m",
    protection_status_en: "Schedule I — Dugong Conservation Reserve",
    bio_note_en: "Grazing telemetry confirmed on Halodule uninervis meadows. High eco-priority."
  }
];

// Marine Conservation Environmental Incidents
const ORCA_MARINE_INCIDENTS = [
  {
    id: "inc-01",
    type: "oil_slick",
    icon: "🛢️",
    title_en: "Minor Fuel Slick Detected by SAR",
    title_hi: "SAR उपग्रह द्वारा ट्रेस किया गया तेल रिसाव",
    title_ta: "எண்ணெய் கசிவு கண்டறியப்பட்டது",
    severity: "warning",
    coords: [15.22, 73.68],
    location_en: "14 NM Offshore Mormugao Shipping Lane",
    desc_en: "Sentinel-1 Synthetic Aperture Radar detected 1.2 sq km hydrocarbon surface film. Containment vessel dispatched."
  },
  {
    id: "inc-02",
    type: "ghost_gear",
    icon: "🕸️",
    title_en: "Derelict Ghost Net Entanglement Risk",
    title_hi: "लावारिस घोस्ट नेट का खतरा",
    title_ta: "கைவிடப்பட்ட வலை ஆபத்து",
    severity: "danger",
    coords: [15.48, 73.60],
    location_en: "Betul Offshore Trawling Boundary",
    desc_en: "Acoustic pingers localized abandoned commercial monofilament gillnet at 24m depth. Coastal salvage unit notified."
  },
  {
    id: "inc-03",
    type: "bleaching",
    icon: "🌡️",
    title_en: "Thermal Stress Watch — Degree Heating Week",
    title_hi: "तापीय तनाव निगरानी (DHW)",
    title_ta: "வெப்பநிலை கண்காணிப்பு",
    severity: "caution",
    coords: [16.02, 73.49],
    location_en: "Malvan Sanctuary South Shoal",
    desc_en: "SST 29.1°C sustained for 5 consecutive days. Degree Heating Weeks (DHW) index at 1.8. Moderate vigilance."
  }
];

window.ORCA_SPECIES_CATALOG = ORCA_SPECIES_CATALOG;
window.ORCA_MARINE_INCIDENTS = ORCA_MARINE_INCIDENTS;
